name: CI with caching

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js (example; you can adapt for Python, etc.)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: cache-a9e6e73

      - name: prime-cache-a9e6e73
        run: |
          if [ "${{ steps.cache-deps.outputs.cache-hit }}" = "true" ]; then
            echo "Cache hit for key cache-a9e6e73"
          else
            echo "Cache miss for key cache-a9e6e73"
          fi
